Employee_Portal/Controllers/DeliveryManagerController.cs
using Employee_Portal.Data;
using Employee_Portal.Models;
using Microsoft.AspNetCore.Mvc;

namespace Employee_Portal.Controllers
{
    public class DeliveryManagerController : Controller
    {
        private readonly ApplicationDbContext _db;
        public DeliveryManagerController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Employee_Details_Role()
        {
            IEnumerable<Employee> objEmployeeList = _db.Employees;
            return View(objEmployeeList);
        }
        public IActionResult Employee_Edit_Role(int id, string Role)
        {
            if (id == 0 || Role == "")
            {
                return NotFound();
            }
            var EmployeeDetails = _db.Employees.Find(id);

            //var categoryFromDbFirst = _db.Categories.FirstOrDefault();
            if (EmployeeDetails == null)
            {
                return NotFound();
            }
            return View(EmployeeDetails);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Employee_Edit_Role(Employee Obj)
        {
            _db.Employees.Update(Obj);
            Console.WriteLine(Obj.Role);
            _db.SaveChanges();
            TempData["success"] = "Role Added Successfully";
            return RedirectToAction("Employee_Details_Role");

        }
    }
}

Employee_Portal/Controllers/EmployeeController.cs
using Employee_Portal.Data;
using Employee_Portal.Models;
using Microsoft.AspNetCore.Mvc;

namespace Employee_Portal.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext _db;
        public EmployeeController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Employee_Details()
        {
            IEnumerable<Employee> objEmployeeList = _db.Employees;
            return View(objEmployeeList);
        }
        public IActionResult Create_Employee()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create_Employee(Employee Obj)
        {
            _db.Employees.Add(Obj); 
            _db.SaveChanges();
            TempData["success"] = "Employee Added Successfully";
            return RedirectToAction("Employee_Details");
        }
        public IActionResult Employee_Edit(int id, string Skill)
        {
            if (id == 0 || Skill == "")
            {
                return NotFound();
            }
            var EmployeeDetails = _db.Employees.Find(id);
            
            //var categoryFromDbFirst = _db.Categories.FirstOrDefault();
            if (EmployeeDetails == null)
            {
                return NotFound();
            }
            return View(EmployeeDetails);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Employee_Edit(Employee Obj)
        {
                _db.Employees.Update(Obj);
                _db.SaveChanges();
                TempData["success"] = "Skill Added Successfully";
                return RedirectToAction("Employee_Details");
       
        }

        
    }
}

Employee_Portal/Controllers/Tech_ManagerController.cs
using Employee_Portal.Data;
using Employee_Portal.Models;
using Microsoft.AspNetCore.Mvc;

namespace Employee_Portal.Controllers
{
    public class Tech_ManagerController : Controller
    {
        private readonly ApplicationDbContext _db;
        public Tech_ManagerController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Employee_Details_Tr()
        {
            IEnumerable<Employee> objEmployeeList = _db.Employees;
            return View(objEmployeeList);
        }
        public IActionResult Skill_Details_Tr()
        {
            IEnumerable<Skill_Id> objEmployeeList = _db.Skill_Ids;
            return View(objEmployeeList);
        }
        public IActionResult Create_Skill_Tr()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create_Skill_Tr(Skill_Id Obj)
        {
            _db.Add(Obj);
            _db.SaveChanges();
            TempData["success"] = "Skill Added Successfully";
            return RedirectToAction("Skill_Details_Tr");
        }
    }
}

Employee_Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee_Portal</title>
    <link rel="stylesheet" href="~/css/Bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Employee_Portal.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand">
                    <img src="https://www.westagilelabs.com/wp-content/uploads/2023/04/WAL_logo1.svg" />
                    </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Employee_Details">Employee List</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">HR/DM/TM</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="DeliveryManager" asp-action="Employee_Details_Role">Delivery Manager</a>
                                <a class="dropdown-item" asp-controller="Tech_Manager" asp-action="Employee_Details_Tr">Tech Manager</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                        </ul>
                    <button type="button" class="btn btn-secondary" fdprocessedid="z2oh">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                    </button>
                        
                    
                    @*<form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit" fdprocessedid="05qgvi">Search</button>
                    </form>*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Employee_Portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>