Employee_Portal/Models/Hr.cs
using System.ComponentModel.DataAnnotations;

namespace Employee_Portal.Models
{
    public class Hr
    {
        [Key]
        public string Hr_UserName { get; set; }
        [Required]
        public string Hr_Password { get; set; }
    }
}

Employee_Portal/Controllers/DeliveryManagerController.cs
using Employee_Portal.Data;
using Employee_Portal.Models;
using Microsoft.AspNetCore.Mvc;

namespace Employee_Portal.Controllers
{
    public class DeliveryManagerController : Controller
    {
        private readonly ApplicationDbContext _db;
        public DeliveryManagerController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Employee_Details_Role()
        {
            IEnumerable<Employee> objEmployeeList = _db.Employees;
            return View(objEmployeeList);
        }
        public IActionResult Employee_Edit_Role(int id, string Role)
        {
            if (id == 0 || Role == "")
            {
                return NotFound();
            }
            var EmployeeDetails = _db.Employees.Find(id);

            //var categoryFromDbFirst = _db.Categories.FirstOrDefault();
            if (EmployeeDetails == null)
            {
                return NotFound();
            }
            return View(EmployeeDetails);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Employee_Edit_Role(Employee Obj)
        {
            _db.Employees.Update(Obj);
            Console.WriteLine(Obj.Role);
            _db.SaveChanges();
            TempData["success"] = "Role Added Successfully";
            return RedirectToAction("Employee_Details_Role");

        }
    }
}

Employee_Portal/Controllers/EmployeeController.cs
using Employee_Portal.Data;
using Employee_Portal.Models;
using Microsoft.AspNetCore.Mvc;

namespace Employee_Portal.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext _db;
        public EmployeeController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Employee_Details()
        {
            IEnumerable<Employee> objEmployeeList = _db.Employees;
            return View(objEmployeeList);
        }
        public IActionResult Create_Employee()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create_Employee(Employee Obj)
        {
            _db.Employees.Add(Obj); 
            _db.SaveChanges();
            TempData["success"] = "Employee Added Successfully";
            return RedirectToAction("Employee_Details");
        }
        public IActionResult Employee_Edit(int id, string Skill)
        {
            if (id == 0 || Skill == "")
            {
                return NotFound();
            }
            var EmployeeDetails = _db.Employees.Find(id);
            
            //var categoryFromDbFirst = _db.Categories.FirstOrDefault();
            if (EmployeeDetails == null)
            {
                return NotFound();
            }
            return View(EmployeeDetails);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Employee_Edit(Employee Obj)
        {
                _db.Employees.Update(Obj);
                _db.SaveChanges();
                TempData["success"] = "Skill Added Successfully";
                return RedirectToAction("Employee_Details");
       
        }

        
    }
}

Employee_Portal/Controllers/HrController.cs
using Employee_Portal.Data;
using Employee_Portal.Models;
using Microsoft.AspNetCore.Mvc;

namespace Employee_Portal.Controllers
{
    public class HrController : Controller
    {
        private readonly ApplicationDbContext _db;
        public HrController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Employee_Details_Hr()
        {
            IEnumerable<Employee> objEmployeeList = _db.Employees;
            return View(objEmployeeList);
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create_Employee_Hr()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create_Employee_Hr(Employee Obj)
        {
            _db.Employees.Add(Obj);
            _db.SaveChanges();
            TempData["success"] = "Employee Added Successfully";
            return RedirectToAction("Employee_Details_Hr");
        }
    }
}

Employee_Portal/Views/Hr/Create_Employee_Hr.cshtml
@model Employee
<form method="post">
    @*<div asp-validation-summary="All"></div>*@
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add Employee</h2>
            <hr />
        </div>
    <div class="mb-3">
            <label asp-for="Employee_Name"></label>
            <input asp-for="Employee_Name" class="form-control" />
            <span asp-validation-for="Employee_Name" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Mail"></label>
        <input asp-for="Mail" class="form-control"  />
        <span asp-validation-for="Mail" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="PhoneNumber"></label>
        <input asp-for="PhoneNumber" class="form-control"  />
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    </div>
        <div class="mb-3">
            <label asp-for="Gender" class="form-label mt-4"></label>
            <select name="Gender" class="form-select" id="exampleSelect1" fdprocessedid="x3t78t">
                <option></option>
                <option>MALE</option>
                <option>FEMALE</option>
                <option>OTHER</option>
            </select>
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>
    <div class="mb-3">
        <label asp-for="DOB"></label>
        <input asp-for="DOB" class="form-control"  />
        <span asp-validation-for="DOB" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Experience"></label>
        <input asp-for="Experience" class="form-control" readonly/>
        <span asp-validation-for="Experience" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Skill"></label>
        <input asp-for="Skill" class="form-control" readonly/>
        <span asp-validation-for="Skill" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Role"></label>
        <input asp-for="Role" class="form-control" readonly/>
        <span asp-validation-for="Role" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
    <a asp-controller="Hr" asp-action="Employee_Details_Hr" class="btn btn-primary" style="width:150px">
        Back To Employee List
    </a>



</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Employee_Portal/Views/Hr/Employee_Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<head>
<style>
    div.a {
        white-space: nowrap;
        width: 260px;
        background-color:mediumseagreen ;
        overflow: hidden;
        text-overflow: ellipsis;
        border: 1px solid #000000;
    }

        div.a:hover {
            overflow: visible;
        }
</style>
</head>
<body>
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6 ">
            <h2 class="text-dar border-dark">EMPLOYEE LIST</h2>
            </div>
                <div class="col-4 text-end">
                    <a asp-controller="Employee" asp-action="Create_Employee" class="btn btn-primary">
                        <i class="bi bi-plus-circle"></i> &nbsp; Add New Employee
                    </a>
                </div>
            <div class="col-6 text-end">
                <a asp-controller="DeliveryManager" asp-action="Employee_Edit_Role" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i> &nbsp; Add New Employee
                </a>
            </div>
        </div>
    </div>
    <br /><br />
    @foreach(var obj in Model)
    {
        <div class="card text-white bg-primary mb-3" style="max-width: 30rem;">
            <div class="card-header">@obj.Employee_Name</div>
            <div class="card-body">
                <h4 class="card-title">Employee Details</h4>
                <label class="text">Id:</label>   <label class="text-end" Name="Id">@obj.Id</label><br>
                <label>Mail:</label>   <label Name="Mail:">@obj.Mail</label><br>
                <label>PhoneNumber:</label>   <label Name="PhoneNumber">@obj.PhoneNumber</label><br>
                <label>Gender:</label>   <label Name="Gender">@obj.Gender</label><br>
                <label>DOB:</label>   <label Name="DOB">@obj.DOB.ToLongDateString()</label><br>
                <label>Experience:</label>   <label Name="Experience">@obj.Experience</label><br>
                <label>Skill:</label>   <label Name="Skill">@obj.Skill</label><br>
                <label class="align-content-between">Role:</label>   <label class="align-content-between" Name="Role">@obj.Role</label><br>
                <div class="w-75 btn btn-group">
                    <a asp-controller="Employee" asp-action="Employee_Edit" asp-route-id="@obj.Id" asp-route-data="@obj.Skill"
                       class="btn btn-secondary" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="left" data-bs-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." data-bs-original-title="Popover Title" fdprocessedid="vdq1fau"><i class="bi bi-plus-circle"></i>Add Skill</a>
                </div>
            </div>
        </div>  
    }
    
    @*<table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                
                <th>
                    Employee Id
                </th>
                <th>
                    Employee Name
                </th>
                <th>
                    Mail Id
                </th>
                <th>
                    Phone Number
                </th>
                <th>
                    Gender
                </th>
                <th>
                    DOB
                </th>
                <th>
                    Experience
                </th>
                <th>
                    Skills
                </th>
                <th>
                    Role
                </th>
                <th>
                    Update Skill
                </th>
            </tr>
        </thead>
        <tbody>
           @* @foreach (var obj in Model)
            {
                //@if()
                <tr>
                    <td width="10%">
                        @obj.Id
                    </td>
                    <td width="10%">
                        @obj.Employee_Name
                    </td>
                    <td width="30%">
                        @obj.Mail
                    </td>
                    <td width="10%">
                        @obj.PhoneNumber
                    </td>
                    <td width="10%">
                        @obj.Gender
                    </td>
                    <td width="20%">
                        @obj.DOB.ToLongDateString()
                    </td>
                    <td width="30%">
                        @obj.Experience
                    </td>
                    <td width="50%">
                        @obj.Skill
                    </td>
                    <td width="60%">
                        @obj.Role
                    </td>
                    <td>
                        <div class="w-75 btn btn-group">
                            <a asp-controller="Employee" asp-action="Employee_Edit" asp-route-id="@obj.Id" asp-route-data="@obj.Skill"
                               class="btn btn-primary mx-2"><i class="bi bi-plus-circle"></i>Add Skill</a>
                          
                        </div>
                    </td>

                </tr>
          @*  }*@
        @*</tbody>*@
    @*</table>*@
    </body>

Employee_Portal/Views/Hr/Employee_Details_Hr.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<head>
    
    <style>
    div.a {
        white-space: nowrap;
        width: 260px;
        background-color:mediumseagreen ;
        overflow: hidden;
        text-overflow: ellipsis;
        border: 1px solid #000000;
    }

        div.a:hover {
            overflow: visible;
        }
</style>
</head>
<body>
<div class="container p-3">
    <div class="row pt-3">
        <div class="col-6 ">
            <h2 class="bg-light" >EMPLOYEE LIST</h2>
            </div>
                <div class="col-6 text-end">
                    <a asp-controller="Hr" asp-action="Create_Employee_Hr" class="btn btn-primary">
                        <i class="bi bi-plus-circle"></i> &nbsp; Add New Employee
                    </a>
                </div>
            
        </div>
    </div>
    <br /><br />
    @foreach(var obj in Model)
    {
        <div class="card text-white bg-primary mb-3" style="max-width: 30rem;">
            <div class="card-header">@obj.Employee_Name</div>
            <div class="card-body">
                <h4 class="card-title">Employee Details</h4>
                <label>Mail:</label>   <label Name="Mail:">@obj.Mail</label><br>
                <label>PhoneNumber:</label>   <label Name="PhoneNumber">@obj.PhoneNumber</label><br>
                <label>Gender:</label>   <label Name="Gender">@obj.Gender</label><br>
                <label>DOB:</label>   <label Name="DOB">@obj.DOB.ToLongDateString()</label><br>
                <label>Experience:</label>   <label Name="Experience">@obj.Experience</label><br>
                <label>Skill:</label>   <label Name="Skill">@obj.Skill</label><br>
                <label class="align-content-between">Role:</label>   <label class="align-content-between" Name="Role">@obj.Role</label><br>
                @*<div class="w-75 btn btn-group">
                    <a asp-controller="Employee" asp-action="Employee_Edit" asp-route-id="@obj.Id" asp-route-data="@obj.Skill"
                       class="btn btn-secondary" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="left" data-bs-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." data-bs-original-title="Popover Title" fdprocessedid="vdq1fau"><i class="bi bi-plus-circle"></i>Add Skill</a>
                </div>*@
            </div>
        </div>  
    }
    
    
    @*<table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                
                <th>
                    Employee Id
                </th>
                <th>
                    Employee Name
                </th>
                <th>
                    Mail Id
                </th>
                <th>
                    Phone Number
                </th>
                <th>
                    Gender
                </th>
                <th>
                    DOB
                </th>
                <th>
                    Experience
                </th>
                <th>
                    Skills
                </th>
                <th>
                    Role
                </th>
                <th>
                    Update Skill
                </th>
            </tr>
        </thead>
        <tbody>
           @* @foreach (var obj in Model)
            {
                //@if()
                <tr>
                    <td width="10%">
                        @obj.Id
                    </td>
                    <td width="10%">
                        @obj.Employee_Name
                    </td>
                    <td width="30%">
                        @obj.Mail
                    </td>
                    <td width="10%">
                        @obj.PhoneNumber
                    </td>
                    <td width="10%">
                        @obj.Gender
                    </td>
                    <td width="20%">
                        @obj.DOB.ToLongDateString()
                    </td>
                    <td width="30%">
                        @obj.Experience
                    </td>
                    <td width="50%">
                        @obj.Skill
                    </td>
                    <td width="60%">
                        @obj.Role
                    </td>
                    <td>
                        <div class="w-75 btn btn-group">
                            <a asp-controller="Employee" asp-action="Employee_Edit" asp-route-id="@obj.Id" asp-route-data="@obj.Skill"
                               class="btn btn-primary mx-2"><i class="bi bi-plus-circle"></i>Add Skill</a>
                          
                        </div>
                    </td>

                </tr>
          @*  }*@
        @*</tbody>*@
    @*</table>*@
    </body>